// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registerUser.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterInfo struct {
	PhoneNum             *string  `protobuf:"bytes,1,req,name=phoneNum" json:"phoneNum,omitempty"`
	UserName             *string  `protobuf:"bytes,2,req,name=userName" json:"userName,omitempty"`
	Pwd                  *string  `protobuf:"bytes,3,req,name=pwd" json:"pwd,omitempty"`
	VerifyCode           *string  `protobuf:"bytes,4,req,name=verifyCode" json:"verifyCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterInfo) Reset()         { *m = RegisterInfo{} }
func (m *RegisterInfo) String() string { return proto.CompactTextString(m) }
func (*RegisterInfo) ProtoMessage()    {}
func (*RegisterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c475af53de30857c, []int{0}
}

func (m *RegisterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterInfo.Unmarshal(m, b)
}
func (m *RegisterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterInfo.Marshal(b, m, deterministic)
}
func (m *RegisterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterInfo.Merge(m, src)
}
func (m *RegisterInfo) XXX_Size() int {
	return xxx_messageInfo_RegisterInfo.Size(m)
}
func (m *RegisterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterInfo proto.InternalMessageInfo

func (m *RegisterInfo) GetPhoneNum() string {
	if m != nil && m.PhoneNum != nil {
		return *m.PhoneNum
	}
	return ""
}

func (m *RegisterInfo) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *RegisterInfo) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *RegisterInfo) GetVerifyCode() string {
	if m != nil && m.VerifyCode != nil {
		return *m.VerifyCode
	}
	return ""
}

type RegisterRespStatus struct {
	Status               *bool    `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	Err                  *string  `protobuf:"bytes,2,req,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRespStatus) Reset()         { *m = RegisterRespStatus{} }
func (m *RegisterRespStatus) String() string { return proto.CompactTextString(m) }
func (*RegisterRespStatus) ProtoMessage()    {}
func (*RegisterRespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c475af53de30857c, []int{1}
}

func (m *RegisterRespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRespStatus.Unmarshal(m, b)
}
func (m *RegisterRespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRespStatus.Marshal(b, m, deterministic)
}
func (m *RegisterRespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRespStatus.Merge(m, src)
}
func (m *RegisterRespStatus) XXX_Size() int {
	return xxx_messageInfo_RegisterRespStatus.Size(m)
}
func (m *RegisterRespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRespStatus proto.InternalMessageInfo

func (m *RegisterRespStatus) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func (m *RegisterRespStatus) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterInfo)(nil), "protobuf.RegisterInfo")
	proto.RegisterType((*RegisterRespStatus)(nil), "protobuf.RegisterRespStatus")
}

func init() { proto.RegisterFile("registerUser.proto", fileDescriptor_c475af53de30857c) }

var fileDescriptor_c475af53de30857c = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x49, 0x2d, 0x0a, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x15, 0x5c, 0x3c, 0x41, 0x50, 0x79, 0xcf, 0xbc, 0xb4, 0x7c,
	0x21, 0x29, 0x2e, 0x8e, 0x82, 0x8c, 0xfc, 0xbc, 0x54, 0xbf, 0xd2, 0x5c, 0x09, 0x46, 0x05, 0x26,
	0x0d, 0xce, 0x20, 0x38, 0x1f, 0x24, 0x57, 0x5a, 0x9c, 0x5a, 0xe4, 0x97, 0x98, 0x9b, 0x2a, 0xc1,
	0x04, 0x91, 0x83, 0xf1, 0x85, 0x04, 0xb8, 0x98, 0x0b, 0xca, 0x53, 0x24, 0x98, 0xc1, 0xc2, 0x20,
	0xa6, 0x90, 0x1c, 0x17, 0x57, 0x59, 0x6a, 0x51, 0x66, 0x5a, 0xa5, 0x73, 0x7e, 0x4a, 0xaa, 0x04,
	0x0b, 0x58, 0x02, 0x49, 0x44, 0xc9, 0x8e, 0x4b, 0x08, 0x66, 0x73, 0x50, 0x6a, 0x71, 0x41, 0x70,
	0x49, 0x62, 0x49, 0x69, 0xb1, 0x90, 0x18, 0x17, 0x5b, 0x31, 0x98, 0x05, 0xb6, 0x9d, 0x23, 0x08,
	0xca, 0x03, 0x99, 0x9f, 0x5a, 0x54, 0x04, 0xb5, 0x16, 0xc4, 0x34, 0x8a, 0xe6, 0x12, 0x0e, 0x42,
	0xf2, 0x59, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x0b, 0xc2, 0x43, 0x20, 0x61, 0x21,
	0x31, 0x3d, 0x98, 0x5f, 0xf5, 0x90, 0x3d, 0x2a, 0x25, 0x83, 0x29, 0x8e, 0x70, 0x06, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0x99, 0x06, 0x4f, 0x35, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegisterUserServiceClient is the client API for RegisterUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterUserServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterInfo, opts ...grpc.CallOption) (*RegisterRespStatus, error)
}

type registerUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegisterUserServiceClient(cc *grpc.ClientConn) RegisterUserServiceClient {
	return &registerUserServiceClient{cc}
}

func (c *registerUserServiceClient) RegisterUser(ctx context.Context, in *RegisterInfo, opts ...grpc.CallOption) (*RegisterRespStatus, error) {
	out := new(RegisterRespStatus)
	err := c.cc.Invoke(ctx, "/protobuf.RegisterUserService/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterUserServiceServer is the server API for RegisterUserService service.
type RegisterUserServiceServer interface {
	RegisterUser(context.Context, *RegisterInfo) (*RegisterRespStatus, error)
}

// UnimplementedRegisterUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterUserServiceServer struct {
}

func (*UnimplementedRegisterUserServiceServer) RegisterUser(ctx context.Context, req *RegisterInfo) (*RegisterRespStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}

func RegisterRegisterUserServiceServer(s *grpc.Server, srv RegisterUserServiceServer) {
	s.RegisterService(&_RegisterUserService_serviceDesc, srv)
}

func _RegisterUserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterUserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RegisterUserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterUserServiceServer).RegisterUser(ctx, req.(*RegisterInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegisterUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RegisterUserService",
	HandlerType: (*RegisterUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _RegisterUserService_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registerUser.proto",
}
