// Code generated by protoc-gen-go. DO NOT EDIT.
// source: verifyCode.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyCodeInfo struct {
	PhoneNum             *string  `protobuf:"bytes,1,req,name=phoneNum" json:"phoneNum,omitempty"`
	VerifyCode           *string  `protobuf:"bytes,2,req,name=verifyCode" json:"verifyCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyCodeInfo) Reset()         { *m = VerifyCodeInfo{} }
func (m *VerifyCodeInfo) String() string { return proto.CompactTextString(m) }
func (*VerifyCodeInfo) ProtoMessage()    {}
func (*VerifyCodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1186c3558ec95ca, []int{0}
}

func (m *VerifyCodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCodeInfo.Unmarshal(m, b)
}
func (m *VerifyCodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCodeInfo.Marshal(b, m, deterministic)
}
func (m *VerifyCodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCodeInfo.Merge(m, src)
}
func (m *VerifyCodeInfo) XXX_Size() int {
	return xxx_messageInfo_VerifyCodeInfo.Size(m)
}
func (m *VerifyCodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCodeInfo proto.InternalMessageInfo

func (m *VerifyCodeInfo) GetPhoneNum() string {
	if m != nil && m.PhoneNum != nil {
		return *m.PhoneNum
	}
	return ""
}

func (m *VerifyCodeInfo) GetVerifyCode() string {
	if m != nil && m.VerifyCode != nil {
		return *m.VerifyCode
	}
	return ""
}

type VerifyCodeRespStatus struct {
	Status               *bool    `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyCodeRespStatus) Reset()         { *m = VerifyCodeRespStatus{} }
func (m *VerifyCodeRespStatus) String() string { return proto.CompactTextString(m) }
func (*VerifyCodeRespStatus) ProtoMessage()    {}
func (*VerifyCodeRespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1186c3558ec95ca, []int{1}
}

func (m *VerifyCodeRespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyCodeRespStatus.Unmarshal(m, b)
}
func (m *VerifyCodeRespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyCodeRespStatus.Marshal(b, m, deterministic)
}
func (m *VerifyCodeRespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyCodeRespStatus.Merge(m, src)
}
func (m *VerifyCodeRespStatus) XXX_Size() int {
	return xxx_messageInfo_VerifyCodeRespStatus.Size(m)
}
func (m *VerifyCodeRespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyCodeRespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyCodeRespStatus proto.InternalMessageInfo

func (m *VerifyCodeRespStatus) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*VerifyCodeInfo)(nil), "protobuf.VerifyCodeInfo")
	proto.RegisterType((*VerifyCodeRespStatus)(nil), "protobuf.VerifyCodeRespStatus")
}

func init() { proto.RegisterFile("verifyCode.proto", fileDescriptor_c1186c3558ec95ca) }

var fileDescriptor_c1186c3558ec95ca = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4b, 0x2d, 0xca,
	0x4c, 0xab, 0x74, 0xce, 0x4f, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0x49, 0xa5, 0x69, 0x4a, 0x3e, 0x5c, 0x7c, 0x61, 0x70, 0x59, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x29,
	0x2e, 0x8e, 0x82, 0x8c, 0xfc, 0xbc, 0x54, 0xbf, 0xd2, 0x5c, 0x09, 0x46, 0x05, 0x26, 0x0d, 0xce,
	0x20, 0x38, 0x5f, 0x48, 0x8e, 0x8b, 0x0b, 0x61, 0x96, 0x04, 0x13, 0x58, 0x16, 0x49, 0x44, 0x49,
	0x8f, 0x4b, 0x04, 0x61, 0x5a, 0x50, 0x6a, 0x71, 0x41, 0x70, 0x49, 0x62, 0x49, 0x69, 0xb1, 0x90,
	0x18, 0x17, 0x5b, 0x31, 0x98, 0x05, 0x36, 0x91, 0x23, 0x08, 0xca, 0x33, 0xda, 0xca, 0xc8, 0x25,
	0x88, 0xd0, 0x10, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xcb, 0x25, 0x18, 0x9c, 0x5a,
	0x82, 0xe6, 0x2c, 0x09, 0x3d, 0x98, 0x9b, 0xf5, 0x50, 0x65, 0xa4, 0xe4, 0xb0, 0xc9, 0x20, 0x59,
	0x1e, 0xc8, 0x25, 0xea, 0x59, 0x8c, 0x90, 0x71, 0x2c, 0x4b, 0xcc, 0xcc, 0x49, 0x4c, 0xca, 0x49,
	0x25, 0xdf, 0x48, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xd8, 0x49, 0x0b, 0x52, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerifyCodeServiceClient is the client API for VerifyCodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifyCodeServiceClient interface {
	SetVerifyCodeInfo(ctx context.Context, in *VerifyCodeInfo, opts ...grpc.CallOption) (*VerifyCodeRespStatus, error)
	IsVerifyCodeAvailable(ctx context.Context, in *VerifyCodeInfo, opts ...grpc.CallOption) (*VerifyCodeRespStatus, error)
}

type verifyCodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerifyCodeServiceClient(cc *grpc.ClientConn) VerifyCodeServiceClient {
	return &verifyCodeServiceClient{cc}
}

func (c *verifyCodeServiceClient) SetVerifyCodeInfo(ctx context.Context, in *VerifyCodeInfo, opts ...grpc.CallOption) (*VerifyCodeRespStatus, error) {
	out := new(VerifyCodeRespStatus)
	err := c.cc.Invoke(ctx, "/protobuf.VerifyCodeService/SetVerifyCodeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifyCodeServiceClient) IsVerifyCodeAvailable(ctx context.Context, in *VerifyCodeInfo, opts ...grpc.CallOption) (*VerifyCodeRespStatus, error) {
	out := new(VerifyCodeRespStatus)
	err := c.cc.Invoke(ctx, "/protobuf.VerifyCodeService/IsVerifyCodeAvailable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyCodeServiceServer is the server API for VerifyCodeService service.
type VerifyCodeServiceServer interface {
	SetVerifyCodeInfo(context.Context, *VerifyCodeInfo) (*VerifyCodeRespStatus, error)
	IsVerifyCodeAvailable(context.Context, *VerifyCodeInfo) (*VerifyCodeRespStatus, error)
}

// UnimplementedVerifyCodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVerifyCodeServiceServer struct {
}

func (*UnimplementedVerifyCodeServiceServer) SetVerifyCodeInfo(ctx context.Context, req *VerifyCodeInfo) (*VerifyCodeRespStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVerifyCodeInfo not implemented")
}
func (*UnimplementedVerifyCodeServiceServer) IsVerifyCodeAvailable(ctx context.Context, req *VerifyCodeInfo) (*VerifyCodeRespStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsVerifyCodeAvailable not implemented")
}

func RegisterVerifyCodeServiceServer(s *grpc.Server, srv VerifyCodeServiceServer) {
	s.RegisterService(&_VerifyCodeService_serviceDesc, srv)
}

func _VerifyCodeService_SetVerifyCodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyCodeServiceServer).SetVerifyCodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VerifyCodeService/SetVerifyCodeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyCodeServiceServer).SetVerifyCodeInfo(ctx, req.(*VerifyCodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerifyCodeService_IsVerifyCodeAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyCodeServiceServer).IsVerifyCodeAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.VerifyCodeService/IsVerifyCodeAvailable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyCodeServiceServer).IsVerifyCodeAvailable(ctx, req.(*VerifyCodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerifyCodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.VerifyCodeService",
	HandlerType: (*VerifyCodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetVerifyCodeInfo",
			Handler:    _VerifyCodeService_SetVerifyCodeInfo_Handler,
		},
		{
			MethodName: "IsVerifyCodeAvailable",
			Handler:    _VerifyCodeService_IsVerifyCodeAvailable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verifyCode.proto",
}
